#!/usr/bin/env bash
# displays numbers from 1 to 100
counter=0
while [ $counter -lt 100 ]; do
	(( counter+=1 ))
	if (( counter % 3 == 0 )) && (( counter % 5 == 0 )); then
		echo "FizzBuzz"
	continue
	elif (( counter % 3 == 0 )); then
		echo "Fizz"
	continue
	elif (( counter % 5 == 0 )); then
		echo "Buzz"
	continue
	fi
	echo "$counter"
done
