#!/usr/bin/env bash
# loops from 1 to 10 using while loop and displays bad luck for the 4th loopiteration, goodluck for the 8th loop iteration and Holberton School for the other iterations.
counter=0
while [ $counter -lt 10 ]; do
	(( counter+=1 ))
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done
